### PR TITLE
381 Test Github Action - Add Optional Upload/Export Step

### PR DESCRIPTION
**Pull request by abrieff**
In the process of testing the devcontainer work, we were forced to make temporary changes to test.yml to be able to test the github action functioning without merging into main. This seemed like worthwhile functionality to keep, so this PR addresses #381 and adds a new (default false) workflow dispatch input that allows you to create a manual run of the build that also runs the archive/export/upload steps.

Looks like this
Screen Shot 2022-08-01 at 11 14 46 AM

### CODE REVIEW

**Comment by abrieff** [comment]
Link to usual build that is run on push to verify default behavior is to not run any of these steps 
https://github.com/NYCPlanning/db-pluto/runs/7614101762?check_suite_focus=true

**Comment by SashaWeinstein** [comment]
I like this change a lot! While we are at it, can we change the name of the workflow from "test" to something like "run"? I've always thought it's mis-named

**Comment by abrieff** [comment]
Agreed, but is it okay if I open a second PR for that? Github is weird about pipeline names, it may break the ability for this one to be tested. Might be worth changing on its own

**Review by SashaWeinstein — APPROVED** [review]
Approved on the condition we change the name of the workflow

**Pull request merged**
