### PR TITLE
Switch to referencing datasets by name

### PR DESCRIPTION
**Pull request by SashaWeinstein**
This addresses issue #386. It's associated with these pull requests in [data library](https://github.com/NYCPlanning/db-data-library/pull/257) and [action-library-archive](https://github.com/NYCPlanning/db-data-library/pull/257). 

I'm going to convert this to draft so we can't merge it until those PR's are merged and the image updated. I wanted to open the PR to make my work visible to everyone

### CODE REVIEW

**Review by td928 — COMMENTED** [review]
@SashaWeinstein think I finally caught up with the full picture. I do wonder since those ymls are very specific to the pluto repo whether they should stay here. But I do see the argument from your side that they are tied to data library. Maybe they should live under different directory from the other common templates.

**Comment by SashaWeinstein** [comment]
Yes that's correct publishing sends to recipes, not the edm-publishing bucket. 
I think a lot of our library templates are specific to particular repos and I'm very against keeping them in the particular repo. I prefer keeping them close to the code that runs them, and I prefer having them in one place for consistency. 
I'm open to organizing the templates in data library into sub-folders, think that would be a nice upgrade.

**Comment by mbh329** [comment]
subfolders sound like a good upgrade but also against moving the templates to pluto

**Comment by SashaWeinstein** [comment]
The question is here is whether to move the folders from pluto, that is the biggest change associated with this upgrade

**Comment by SashaWeinstein** [comment]
Once the [data library PR to automatically publish a new image](https://github.com/NYCPlanning/db-data-library/pull/262) is in then I will run it and this should work

**Comment by SashaWeinstein** [comment]
Hey @mbh329 @td928 want to flag that this is ready to be merged in. Once this is merged and the action library PR are merged in then our upgrades to the publishing workflow will be wrapped up.

**Review by td928 — APPROVED** [review]

**Pull request merged**
