### PR TITLE
adding 3 manual corrections to address large increase in number unitsres

### PR DESCRIPTION
**Pull request by AmandaDoyle**
adding 3 manual corrections to address large increase in number unitsres for 3 records.

### CODE REVIEW

**Review by SashaWeinstein — COMMENTED** [review]
The second and third corrections were applied. BBL `1011637503` has original unitres of 21560, I think the old value was supposed to be 21560 instead of 2156?

**Comment by AmandaDoyle** [comment]
@SashaWeinstein  I think this may take more investigating.  See screenshot attached.  What value do you have on your local build
Screen Shot 2022-10-31 at 3 48 29 PM

**Comment by SashaWeinstein** [comment]
That's what I have. The corrections sheet for this bbl has 2156 as the old value so it doesn't get corrected. My assumption is that the old value in the corrections should is supposed to be 21560 and then all three we be applied and the final build will be as expected

**Comment by AmandaDoyle** [comment]
Ah I'm sorry.  I misunderstood.  See fix in latest commit

**Review by SashaWeinstein — APPROVED** [review]
Awesome, that works on my machine

**Pull request merged**
